_BASE_: "Base-CenterNet2.yaml"
DATASETS:
    TEST: ('waymo_test_tut',)
MODEL:
    ROI_HEADS:
        BATCH_SIZE_PER_IMAGE: 2
        NUM_CLASSES: 3
DATALOADER:
    NUM_WORKERS: 6
SOLVER:
    IMS_PER_BATCH : 2


